/**
 * 演示种子数据：首次访问时写入 localStorage。
 * 均为常见中国海域海洋生物，经纬度为大致分布中心点。
 */
const SEED_SPECIES = [
  {
    id: 1001,
    name: '中华白海豚',
    scientificName: 'Sousa chinensis',
    alias: '白鱀豚、印太驼海豚',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '哺乳纲',
    order: '鲸目',
    family: '海豚科',
    genus: '驼海豚属',
    speciesName: '中华白海豚',
    conservationStatus: 'VU',
    protectionLevel: '一级',
    distribution: '珠江口及南海北部沿岸海域',
    longitude: '113.50',
    latitude: '22.30',
    habitat: '近岸浅水海域、河口三角洲',
    diet: '鱼类、头足类、甲壳类',
    behavior: '群居，常跃出水面，幼体呈暗灰色',
    reproduction: '胎生，哺乳期约1年',
    features: '成体通体粉白色，吻突狭长，背鳍后缘凹陷',
    remark: '中国国家一级保护动物，珠江口水域为重要栖息地',
    videoUrl: '',
    reference: '中国生物物种名录(2023年版). 中国科学院生物多样性委员会.',
    image: ''
  },
  {
    id: 1002,
    name: '鲸鲨',
    scientificName: 'Rhincodon typus',
    alias: '豆腐鲨、大憨鲨',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '软骨鱼纲',
    order: '须鲨目',
    family: '鲸鲨科',
    genus: '鲸鲨属',
    speciesName: '鲸鲨',
    conservationStatus: 'EN',
    protectionLevel: '二级',
    distribution: '南海海域，季节性洄游',
    longitude: '114.50',
    latitude: '20.00',
    habitat: '热带和温带开阔海域',
    diet: '浮游生物、小型鱼类、磷虾',
    behavior: '滤食性，性格温和，常在表层缓慢游动',
    reproduction: '卵胎生',
    features: '现存最大的鱼类，体表布满白色斑点与条纹',
    remark: '2021年列入国家重点保护野生动物名录（二级）',
    videoUrl: '',
    reference: '国家重点保护野生动物名录(2021年版). 国家林业和草原局.',
    image: ''
  },
  {
    id: 1003,
    name: '玳瑁',
    scientificName: 'Eretmochelys imbricata',
    alias: '瑇瑁、鹰嘴海龟',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '爬行纲',
    order: '龟鳖目',
    family: '海龟科',
    genus: '玳瑁属',
    speciesName: '玳瑁',
    conservationStatus: 'CR',
    protectionLevel: '一级',
    distribution: '南海西沙群岛及华南沿海',
    longitude: '112.30',
    latitude: '16.50',
    habitat: '珊瑚礁海域，以礁区为活动中心',
    diet: '海绵、水母、海葵等',
    behavior: '洄游性海龟，多在礁区觅食',
    reproduction: '卵生，夜间上岸产卵',
    features: '背甲呈覆瓦状排列，具黄褐相间斑纹，鹰嘴状喙',
    remark: '背甲曾遭猎捕用于工艺品，种群急剧下降',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1004,
    name: '儒艮',
    scientificName: 'Dugong dugon',
    alias: '美人鱼、海牛',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '哺乳纲',
    order: '海牛目',
    family: '儒艮科',
    genus: '儒艮属',
    speciesName: '儒艮',
    conservationStatus: 'VU',
    protectionLevel: '一级',
    distribution: '北部湾广西沿岸及雷州半岛海域',
    longitude: '109.00',
    latitude: '21.00',
    habitat: '海草床生境，浅水海域',
    diet: '海草为主',
    behavior: '群居，摄食时缓慢移动，浮出水面呼吸',
    reproduction: '胎生，妊娠期约13-14个月',
    features: '体呈纺锤形，尾鳍分叉，吻端下弯',
    remark: '唯一一种植食性海洋哺乳动物，俗称"美人鱼"',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1005,
    name: '绿海龟',
    scientificName: 'Chelonia mydas',
    alias: '绿蠵龟',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '爬行纲',
    order: '龟鳖目',
    family: '海龟科',
    genus: '海龟属',
    speciesName: '绿海龟',
    conservationStatus: 'EN',
    protectionLevel: '一级',
    distribution: '南海及华南沿海沙滩产卵场',
    longitude: '113.80',
    latitude: '22.00',
    habitat: '沿海浅水区，产卵期上岸',
    diet: '海草、藻类，幼体亦食小型动物',
    behavior: '长距离洄游，繁殖期返回出生沙滩',
    reproduction: '卵生，一季可产卵数次',
    features: '成体背甲褐色或橄榄色，脂肪呈绿色',
    remark: '我国多个沿海保护区开展人工孵化保育',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1006,
    name: '鹿角珊瑚',
    scientificName: 'Acropora sp.',
    alias: '枝状珊瑚',
    kingdom: '动物界',
    phylum: '刺胞动物门',
    classLevel: '珊瑚虫纲',
    order: '石珊瑚目',
    family: '鹿角珊瑚科',
    genus: '鹿角珊瑚属',
    speciesName: '鹿角珊瑚',
    conservationStatus: 'CR',
    protectionLevel: '二级',
    distribution: '西沙群岛、南沙群岛珊瑚礁',
    longitude: '112.50',
    latitude: '16.80',
    habitat: '造礁珊瑚礁盘，热带浅海',
    diet: '虫黄藻光合作用为主，兼食浮游生物',
    behavior: '群体固着生活，快速分枝生长',
    reproduction: '有性繁殖（同步排卵）与无性繁殖',
    features: '分枝呈鹿角状，生长快，是珊瑚礁主要造礁种类',
    remark: '全球变暖与白化事件使其种群严重衰退',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1007,
    name: '中华鲟',
    scientificName: 'Acipenser sinensis',
    alias: '鲟鱼、鳇鱼',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '硬骨鱼纲',
    order: '鲟形目',
    family: '鲟科',
    genus: '鲟属',
    speciesName: '中华鲟',
    conservationStatus: 'CR',
    protectionLevel: '一级',
    distribution: '长江口及近海，溯河洄游',
    longitude: '122.00',
    latitude: '31.00',
    habitat: '大型河流河口及大陆架近海',
    diet: '底栖无脊椎动物、小鱼虾',
    behavior: '溯河洄游，定期生殖洄游',
    reproduction: '卵生，溯河到上游产卵',
    features: '古老珍稀鱼类，体被五行骨板，被誉为"水中大熊猫"',
    remark: '长江旗舰物种，野生种群亟待保护',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1008,
    name: '大黄鱼',
    scientificName: 'Larimichthys crocea',
    alias: '黄花鱼',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '硬骨鱼纲',
    order: '鲈形目',
    family: '石首鱼科',
    genus: '黄鱼属',
    speciesName: '大黄鱼',
    conservationStatus: 'VU',
    protectionLevel: '二级',
    distribution: '东海、南海沿岸及近海',
    longitude: '122.00',
    latitude: '28.00',
    habitat: '沿岸及近海，随水温季节性洄游',
    diet: '小型鱼类、虾蟹、头足类',
    behavior: '结群洄游，生殖时发出"咕咕"声',
    reproduction: '卵生，春夏在近岸产卵',
    features: '体金黄，尾鳍尖长，为我国四大海产之一',
    remark: '过度捕捞曾致种群衰退，现已规模化人工养殖',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1009,
    name: '文昌鱼',
    scientificName: 'Branchiostoma belcheri',
    alias: '白氏文昌鱼、海矛',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '头索动物亚门',
    order: '文昌鱼目',
    family: '文昌鱼科',
    genus: '文昌鱼属',
    speciesName: '文昌鱼',
    conservationStatus: 'NT',
    protectionLevel: '二级',
    distribution: '厦门海域及华南沿海沙质底',
    longitude: '118.00',
    latitude: '24.50',
    habitat: '近岸浅水沙底环境',
    diet: '滤食浮游生物、有机碎屑',
    behavior: '营半穴居生活，昼伏夜出',
    reproduction: '体外受精，幼体自由游泳',
    features: '脊索动物演化研究的重要代表，被称为"活化石"',
    remark: '对研究脊椎动物起源具有重要科学价值',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1010,
    name: '秋茄',
    scientificName: 'Kandelia obovata',
    alias: '水笔仔',
    kingdom: '植物界',
    phylum: '被子植物门',
    classLevel: '双子叶植物纲',
    order: '红树目',
    family: '红树科',
    genus: '秋茄属',
    speciesName: '秋茄',
    conservationStatus: 'LC',
    protectionLevel: '三级',
    distribution: '湛江红树林、福建至海南沿海滩涂',
    longitude: '110.40',
    latitude: '21.20',
    habitat: '潮间带滩涂，红树林生态系统优势种',
    diet: '-',
    behavior: '胎生苗，滩涂先锋植物',
    reproduction: '胎生繁殖，胚轴成熟后脱落扎根',
    features: '红树林常见树种，支柱根发达，耐盐碱',
    remark: '湛江红树林国家级自然保护区主要树种之一',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1011,
    name: '中华鲎',
    scientificName: 'Tachypleus tridentatus',
    alias: '马蹄蟹、鲎',
    kingdom: '动物界',
    phylum: '节肢动物门',
    classLevel: '肢口纲',
    order: '剑尾目',
    family: '鲎科',
    genus: '鲎属',
    speciesName: '中华鲎',
    conservationStatus: 'EN',
    protectionLevel: '二级',
    distribution: '中国东南沿海至北部湾海域',
    longitude: '109.50',
    latitude: '21.30',
    habitat: '沙质海底浅水区',
    diet: '底栖蠕虫、小贝类、动物尸体',
    behavior: '晨昏在潮间带活动，繁殖期上岸产卵',
    reproduction: '卵生，雌鲎产卵于沙滩',
    features: '体被坚硬甲壳，有"活化石"之称',
    remark: '血液提取物用于细菌内毒素检测，种群锐减',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1012,
    name: '棱皮龟',
    scientificName: 'Dermochelys coriacea',
    alias: '革龟、舢板龟',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '爬行纲',
    order: '龟鳖目',
    family: '棱皮龟科',
    genus: '棱皮龟属',
    speciesName: '棱皮龟',
    conservationStatus: 'VU',
    protectionLevel: '一级',
    distribution: '热带与亚热带开阔海域',
    longitude: '114.00',
    latitude: '20.50',
    habitat: '开阔大洋，远洋洄游',
    diet: '水母、海鞘等软体动物',
    behavior: '长途洄游，可下潜至千米深',
    reproduction: '卵生，夜间上沙滩产卵',
    features: '现存最大的海龟，背甲革质无盾片',
    remark: '主食水母，误食塑料垃圾是主要威胁',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1013,
    name: '蓝鲸',
    scientificName: 'Balaenoptera musculus',
    alias: '剃刀鲸',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '哺乳纲',
    order: '鲸目',
    family: '须鲸科',
    genus: '须鲸属',
    speciesName: '蓝鲸',
    conservationStatus: 'EN',
    protectionLevel: '一级',
    distribution: '南海远洋水域，偶见于东海',
    longitude: '115.00',
    latitude: '19.00',
    habitat: '开阔大洋',
    diet: '磷虾等浮游甲壳类',
    behavior: '滤食性，喷出的水柱可达9米高',
    reproduction: '胎生，妊娠期约10-12个月',
    features: '地球上现存最大的动物，体长可达30米',
    remark: '我国海域近年有搁浅记录，极其珍稀',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1014,
    name: '宽吻海豚',
    scientificName: 'Tursiops truncatus',
    alias: '瓶鼻海豚',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '哺乳纲',
    order: '鲸目',
    family: '海豚科',
    genus: '宽吻海豚属',
    speciesName: '宽吻海豚',
    conservationStatus: 'LC',
    protectionLevel: '二级',
    distribution: '中国沿海及台湾海峡',
    longitude: '114.50',
    latitude: '22.50',
    habitat: '近岸与近海水域',
    diet: '鱼类、乌贼、甲壳类',
    behavior: '群居，聪明好学，常跃出水面',
    reproduction: '胎生，哺乳期一年余',
    features: '吻部短而圆钝，体色背深腹浅',
    remark: '海洋馆常见的表演物种',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1015,
    name: '线纹海马',
    scientificName: 'Hippocampus kelloggi',
    alias: '克氏海马、大海马',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '硬骨鱼纲',
    order: '海龙目',
    family: '海龙科',
    genus: '海马属',
    speciesName: '线纹海马',
    conservationStatus: 'VU',
    protectionLevel: '二级',
    distribution: '南海北部至北部湾近岸',
    longitude: '111.00',
    latitude: '21.00',
    habitat: '海草床、珊瑚礁及近岸浅水',
    diet: '小型甲壳动物、桡足类',
    behavior: '游泳缓慢，常以卷曲尾部固定于海草',
    reproduction: '雄性育儿囊孵卵，雄性妊娠',
    features: '头部形似马头，体表具环状骨片',
    remark: '名贵中药材，已列入 CITES 附录',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1016,
    name: '大砗磲',
    scientificName: 'Tridacna gigas',
    alias: '巨型砗磲、车磲',
    kingdom: '动物界',
    phylum: '软体动物门',
    classLevel: '双壳纲',
    order: '帘蛤目',
    family: '砗磲科',
    genus: '砗磲属',
    speciesName: '大砗磲',
    conservationStatus: 'VU',
    protectionLevel: '一级',
    distribution: '西沙群岛、南沙群岛珊瑚礁',
    longitude: '112.30',
    latitude: '16.50',
    habitat: '珊瑚礁浅水区，半埋于礁沙',
    diet: '虫黄藻光合作用为主',
    behavior: '固着生活，外套膜色彩斑斓',
    reproduction: '卵生，体外受精',
    features: '世界上最大的双壳贝类，壳重可达200公斤',
    remark: '列入国家一级保护动物',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1017,
    name: '三斑宅泥鱼',
    scientificName: 'Dascyllus trimaculatus',
    alias: '三点白、黑鲷',
    kingdom: '动物界',
    phylum: '脊索动物门',
    classLevel: '硬骨鱼纲',
    order: '鲈形目',
    family: '雀鲷科',
    genus: '宅泥鱼属',
    speciesName: '三斑宅泥鱼',
    conservationStatus: 'LC',
    protectionLevel: '',
    distribution: '南海及东海南部珊瑚礁',
    longitude: '112.80',
    latitude: '17.00',
    habitat: '珊瑚礁浅水区',
    diet: '藻类、浮游动物、小型无脊椎动物',
    behavior: '群居，幼鱼常躲藏于海葵中',
    reproduction: '卵生，成对繁殖',
    features: '体色黑褐色，头顶及体侧具白色斑块',
    remark: '常见的珊瑚礁观赏鱼',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1018,
    name: '中国龙虾',
    scientificName: 'Panulirus stimpsoni',
    alias: '青龙虾、中华龙虾',
    kingdom: '动物界',
    phylum: '节肢动物门',
    classLevel: '软甲纲',
    order: '十足目',
    family: '龙虾科',
    genus: '龙虾属',
    speciesName: '中国龙虾',
    conservationStatus: 'LC',
    protectionLevel: '',
    distribution: '南海北部、东海及福建沿海',
    longitude: '118.00',
    latitude: '24.00',
    habitat: '岩礁海底及珊瑚礁间隙',
    diet: '贝类、小蟹、腐殖质',
    behavior: '夜行性，昼伏于礁缝',
    reproduction: '卵生，雌体抱卵孵化',
    features: '无螯虾类，体色青绿带深斑',
    remark: '名贵海珍品，市场价值高',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1019,
    name: '真蛸',
    scientificName: 'Octopus vulgaris',
    alias: '章鱼、八爪鱼',
    kingdom: '动物界',
    phylum: '软体动物门',
    classLevel: '头足纲',
    order: '八腕目',
    family: '章鱼科',
    genus: '蛸属',
    speciesName: '真蛸',
    conservationStatus: 'LC',
    protectionLevel: '',
    distribution: '中国沿海广布',
    longitude: '120.00',
    latitude: '30.00',
    habitat: '岩礁、沙泥海底',
    diet: '蟹、虾、贝类及鱼类',
    behavior: '独居，伪装能力强，善钻洞',
    reproduction: '卵生，雌体护卵至孵化',
    features: '八条腕足，体色随环境快速变化',
    remark: '具有极高的认知能力',
    videoUrl: '',
    reference: '',
    image: ''
  },
  {
    id: 1020,
    name: '海月水母',
    scientificName: 'Aurelia aurita',
    alias: '月亮水母',
    kingdom: '动物界',
    phylum: '刺胞动物门',
    classLevel: '钵水母纲',
    order: '旗口水母目',
    family: '海月水母科',
    genus: '海月水母属',
    speciesName: '海月水母',
    conservationStatus: 'LC',
    protectionLevel: '',
    distribution: '中国近海及河口海域',
    longitude: '121.00',
    latitude: '31.00',
    habitat: '近岸表层水域',
    diet: '浮游动物、桡足类、小鱼卵',
    behavior: '随洋流漂浮，常群体出现',
    reproduction: '有性繁殖与水螅体无性繁殖交替',
    features: '伞状透明体，可见四叶马蹄形生殖腺',
    remark: '春季沿海常见，指示水域富营养化',
    videoUrl: '',
    reference: '',
    image: ''
  }
];

/**
 * 模块一：预置用户（密码均为 123456，纯演示用途）
 */
const SEED_USERS = [
  { id: 1, username: 'admin', password: '123456', nickname: '系统管理员', role: 'admin', status: 'active', email: 'admin@gdou.edu.cn', createdAt: '2024-01-05' },
  { id: 2, username: 'teacher', password: '123456', nickname: '李老师', role: 'researcher', status: 'active', email: 'teacher@gdou.edu.cn', createdAt: '2024-01-10' },
  { id: 3, username: 'student', password: '123456', nickname: '张同学', role: 'student', status: 'active', email: 'student@gdou.edu.cn', createdAt: '2024-02-12' },
  { id: 4, username: 'public', password: '123456', nickname: '海洋爱好者', role: 'public', status: 'active', email: 'pub@example.com', createdAt: '2024-03-03' },
  { id: 5, username: 'waiting', password: '123456', nickname: '陈同学', role: 'student', status: 'pending', email: 'chen@gdou.edu.cn', createdAt: '2026-09-01' }
];

const ROLE_LABELS = {
  admin: '管理员',
  researcher: '科研人员',
  student: '学生',
  public: '公众'
};

/**
 * 模块三a：预置海洋生态系统
 */
const SEED_ECOSYSTEMS = [
  { id: 1, name: '西沙珊瑚礁生态系统', type: '造礁珊瑚礁', location: '南海西沙群岛', longitude: '112.30', latitude: '16.80', area: 120, description: '热带造礁珊瑚生态系统，海洋生物多样性最高的生态类型', owner: 'teacher', createdAt: '2024-01-20' },
  { id: 2, name: '湛江红树林生态系统', type: '红树林', location: '广东湛江高桥', longitude: '109.72', latitude: '21.53', area: 180, description: '中国面积最大的红树林自然保护区，重要的候鸟与底栖生物栖息地', owner: 'teacher', createdAt: '2024-02-05' },
  { id: 3, name: '北部湾海草床', type: '海草床', location: '广西北部湾', longitude: '109.15', latitude: '21.30', area: 80, description: '儒艮的重要觅食地，海草覆盖的浅水海域', owner: 'teacher', createdAt: '2024-02-20' },
  { id: 4, name: '南海深海生态系统', type: '深海', location: '南海深海盆地', longitude: '116.50', latitude: '18.00', area: 300, description: '深海热泉与冷泉生态系统的探索区域', owner: 'teacher', createdAt: '2024-03-12' },
  { id: 5, name: '雷州湾滩涂湿地', type: '滩涂湿地', location: '广东雷州半岛', longitude: '110.02', latitude: '20.90', area: 90, description: '潮间带滩涂，越冬候鸟与滩涂贝类的栖息地', owner: 'teacher', createdAt: '2024-04-01' }
];

const ECOSYSTEM_TYPES = ['造礁珊瑚礁', '红树林', '海草床', '深海', '滩涂湿地', '河口湿地'];

/**
 * 模块三b：预置观测记录（speciesSeen 关联模块二物种 id）
 */
const SEED_OBSERVATIONS = [
  {
    id: 1, ecoId: 1, date: '2024-04-15', longitude: '112.28', latitude: '16.55',
    observer: '李老师', temp: 27.5, salinity: 34, depth: 8,
    speciesSeen: [
      { speciesId: 1006, count: 0, behavior: '珊瑚覆盖率约35%，生长健康' },
      { speciesId: 1016, count: 15, behavior: '成体分布于礁坪浅水处' },
      { speciesId: 1017, count: 300, behavior: '集群游动于珊瑚枝间' },
      { speciesId: 1003, count: 2, behavior: '在礁缘觅食海绵' }
    ],
    remark: '西沙珊瑚礁季度生态调查',
    createdAt: '2024-04-15'
  },
  {
    id: 2, ecoId: 2, date: '2024-05-20', longitude: '109.72', latitude: '21.53',
    observer: '李老师', temp: 28.2, salinity: 22, depth: 1,
    speciesSeen: [
      { speciesId: 1010, count: 0, behavior: '秋茄为优势树种，胎生苗更新良好' }
    ],
    remark: '湛江红树林样带调查',
    createdAt: '2024-05-20'
  },
  {
    id: 3, ecoId: 3, date: '2024-06-10', longitude: '109.15', latitude: '21.30',
    observer: '李老师', temp: 29.0, salinity: 30, depth: 3,
    speciesSeen: [
      { speciesId: 1004, count: 3, behavior: '儒艮群体在海草场觅食' },
      { speciesId: 1015, count: 20, behavior: '分布在海草床边缘' }
    ],
    remark: '北部湾海草床儒艮专项监测',
    createdAt: '2024-06-10'
  },
  {
    id: 4, ecoId: 4, date: '2024-07-05', longitude: '116.50', latitude: '18.00',
    observer: '李老师', temp: 4.0, salinity: 35, depth: 1200,
    speciesSeen: [
      { speciesId: 1013, count: 1, behavior: '深潜个体，水下声学记录' }
    ],
    remark: '南海深海生态系统科考',
    createdAt: '2024-07-05'
  },
  {
    id: 5, ecoId: 1, date: '2024-08-18', longitude: '113.60', latitude: '22.10',
    observer: '李老师', temp: 30.1, salinity: 33, depth: 5,
    speciesSeen: [
      { speciesId: 1005, count: 4, behavior: '成体在近岸浅水觅食海草' },
      { speciesId: 1014, count: 8, behavior: '跟随调查船跃出水面' }
    ],
    remark: '南海珊瑚礁近岸水域巡航调查',
    createdAt: '2024-08-18'
  }
];
